name: Presenting to Win
favicon: null
layout_spectrum: 0.1811067
typography_spectrum: 0.8188063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b1320'
    - '#e3ddc7'
    - '#c81431'
    - '#524e32'
    - '#3da0c2'
  brandStrength: 0.7010403
  lightness: 0.625
  saturation: 0.7544689
  rhythmicContrast: 0.7727639
purpose: []
