layout_spectrum: 0.1811067
typography_spectrum: 0.8188063
color:
  saturation: 0.7544689
  lightness: 0.5408465
  brandStrength: 0.7010403
  rhythmicContrast: 0.7727639
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Presenting to Win
