name: Presenting to Win
favicon: null
layout_spectrum: 0.1811067
typography_spectrum: 0.8188063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1d1a'
    - '#f7f6f2'
    - '#d9cbc9'
    - '#9f8783'
    - '#97270d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
