collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6729323
color:
  saturation: 0.4709989
  brandStrength: 0.7010403
  lightness: 0.7781955
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 0.4215897
layout_spectrum: 0.2572502
name: Presenting to Win
